Eigenvalues and eigenvectors for matrices are two of the most-importance concepts of linear algebra. The word "eigen" is German for "own".

An eigenvector of $A$ is a vector that points in its own (or complete opposite) direction upon multiplication by $A$.

In [9]:
A = np.array([[-1, 2, 4],
             [0, 7, 12],
             [0, 0, -4]])

# if you multiply A with the 1st vector in the matrix below, then you will get a eigenvalue of 7.
eigmat = np.array([0.2425356, 0.9701425, 0.0000000])

# to find out, just do a scalar of 7 multiplied by the eigmat array.
np.round(A@eigmat - 7*eigmat)

array([0., 0., 0.])

Scalar Multiplies of Eigenvectors are Eigenvectors

In the example above, you can just scale A down to any multiples using scalar multiplication on A. 


In [10]:
np.round(1/2*A@eigmat - 1/2*7*eigmat)

array([0., 0., 0.])

In [11]:
np.round(3*A@eigmat - 3*7*eigmat)

array([0., 0., 0.])

So, we can reasonably conclude that the scalar $\lambda$ is an eigenvalue of $A$ with associated eigenvector $\vec{v} \neq \vec{0}$



### Properties of Solutions to Eigenvalue/Eigenvector

1. An $n$ by $n$ matrix $A$ has, up to multiplicity, $n$ eigenvalues
1. Even if A is a matrix consisting entirely of real numbers, some (or all) of its eigenvalues
could be complex numbers.
1. All complex eigenvalues must come in conjugate pairs, though, like 1 + 2$i$ and 1 − 2$i$.

In [20]:
# to find the eigens, we can just call np.linalg.eig for square matrices

eigvals = np.linalg.eig(A)[0]
eigvecs = np.linalg.eig(A)[1]

print (f"eigenvalues: \n{eigvals} \n")
print (f"eigenvectors: \n{eigvecs}")

eigenvalues: 
[-1.  7. -4.] 

eigenvectors: 
[[ 1.          0.24253563 -0.37898096]
 [ 0.          0.9701425  -0.68216573]
 [ 0.          0.          0.62531859]]


Here, we will show that the $\lambda$ of matrix $A$ satisfy the property that the matrix $\lambda I - A$ is not invertible, with determinant equal to zero.

In [25]:
# show that lambda of A satisfy the property that the matrix
A = np.array([[1,2],
              [1,1]])
eigenvals = np.linalg.eig(A)[0]
identity = np.identity(2)
print (round(np.linalg.det(eigenvals[0]*identity - A), 3))
print (round(np.linalg.det(eigenvals[1]*identity - A),3))

-0.0
-0.0


If $\lambda_1$, $\lambda_2$, $\lambda_3$, ..., $\lambda_n$ of $A$ are distinct and $\vec v_1$, $\vec v_2$, ..., $\vec v_n$, then this set of vectors forms the basis for the set of n-dimensional vectors. 

Thus, matrix $A$ having the above bases would mean that every $n$-dimensional vector can be expressed as a linear combination of these vectors. This is how principle component analysis is done, where the first eigenvector (the one with highest eigenvalue) is the most important "variable".

When  you have $A\vec{x}$, and using the fact that $A\vec v_j = \lambda_j \vec v_j$, then we can do decomposition - 

$A\vec{x} = c_1 \lambda _1 \vec v_1 + c_2 \lambda _2 \vec v_2 + ... + c_n \lambda _n \vec v_n$

Multiplying iteratively - 

$AA\vec x$

$ = A(c_1 \lambda _1 \vec v_1 + c_2 \lambda _2 \vec v_2 + ... + c_n \lambda _n \vec v_n)$

$ = c_1 \lambda ^2_1 \vec v_1 + c_2 \lambda ^2_2 \vec v_2 + ... + c_n \lambda ^2_n \vec v_n$

or more generally - 

$A^tA\vec x = c_1 \lambda ^t_1 \vec v_1 + c_2 \lambda ^t_2 \vec v_2 + ... + c_n \lambda ^t_n \vec v_n$

