# Linear Algebra in Python

1. Introduction to Linear Algebra
1. Matrix-Vector Equations
1. Eigenvalues and Eigenvectors
1. Principal Component Analysis

The content is taken from "Linear Algebra for Data Science in R" in Datacamp. The purpose is to take the excellent content and code and put them here in Python code.

## Matrix-Vector Equations

$A\vec{x} = \vec{b}$

We will work with a matrix-vector model for team strength in the Women's National Basketball Association (WNBA) at the conclusion of the 2017 season. These team strengths can be used to predict who will win a match between any two teams, for example, using machine learning.


In [75]:
import pandas as pd
import numpy as np
import sympy 

# load up the massey dataset
wnba_massey = pd.read_csv("data/wnba_massey.csv")

# load up differentials dataset
wnba_diff = pd.read_csv("data/wnba_diff.csv")

wnba_massey.set_index("Team", inplace = True)
wnba_diff.set_index("Team", inplace = True)

In [76]:
wnba_massey.head()

Atlanta  Chicago  Connecticut  Dallas  Indiana  Los.Angeles  \
Team                                                                       
Atlanta           33       -4           -2      -3       -3           -3   
Chicago           -4       33           -3      -3       -3           -3   
Connecticut       -2       -3           34      -3       -3           -3   
Dallas            -3       -3           -3      34       -3           -4   
Indiana           -3       -3           -3      -3       33           -3   

             Minnesota  New.York  Phoenix  San.Antonio  Seattle  Washington  
Team                                                                         
Atlanta             -3        -3       -3           -3       -3          -3  
Chicago             -2        -3       -3           -3       -3          -3  
Connecticut         -3        -4       -4           -3       -3          -3  
Dallas              -3        -3       -2           -3       -3          -4  
Indiana             -3        -3       -3           -3       -2          -4

In [77]:
wnba_diff.head()

Differential
Team                     
Atlanta              -135
Chicago              -171
Connecticut           152
Dallas               -104
Indiana              -308

The sum of each column should be zero. Likewise in differentials.

In [78]:
print (f"Sum of Atlanta column: {wnba_massey['Atlanta'].sum()}")
print (f"Sum of differentials column: {wnba_diff['Differential'].sum()}")

Sum of Atlanta column: 0
Sum of differentials column: 0


In [79]:
wnba_massey_np = wnba_massey.to_numpy()
wnba_massey_np

array([[33, -4, -2, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-4, 33, -3, -3, -3, -3, -2, -3, -3, -3, -3, -3],
       [-2, -3, 34, -3, -3, -3, -3, -4, -4, -3, -3, -3],
       [-3, -3, -3, 34, -3, -4, -3, -3, -2, -3, -3, -4],
       [-3, -3, -3, -3, 33, -3, -3, -3, -3, -3, -2, -4],
       [-3, -3, -3, -4, -3, 41, -8, -3, -6, -3, -2, -3],
       [-3, -2, -3, -3, -3, -8, 41, -3, -4, -3, -3, -6],
       [-3, -3, -4, -3, -3, -3, -3, 34, -3, -2, -3, -4],
       [-3, -3, -4, -2, -3, -6, -4, -3, 38, -3, -4, -3],
       [-3, -3, -3, -3, -3, -3, -3, -2, -3, 32, -4, -2],
       [-3, -3, -3, -3, -2, -2, -3, -3, -4, -4, 33, -3],
       [-3, -3, -3, -4, -4, -3, -6, -4, -3, -2, -3, 38]], dtype=int64)

Is the matrix invertible? If you run the inv function, you will find that the inverse matrix is a singular value - 3.12749974e+13. This can't be right. 

Another thing is that if you try to work out the row reduced echelon form for this matrix, you will find that there it is not full rank. 

Lastly, the rows are all a linear combination of the other rows. Eg, the first row is the linear combination of 1* all the other rows.

Hence, actually this is matrix is not invertible.

In [119]:
# try to invert this matrix - you get singular value for all the cells. WTF?
np.linalg.pinv(wnba_massey_np)

array([[ 0.02550536, -0.00154152, -0.00306778, -0.00231444, -0.00231485,
        -0.0023182 , -0.00233334, -0.00233523, -0.0023339 , -0.00231419,
        -0.00231523, -0.00231668],
       [-0.00154152,  0.02550234, -0.00233635, -0.00231753, -0.00231617,
        -0.00238962, -0.00295924, -0.00231672, -0.00233643, -0.00231336,
        -0.00231326, -0.00236215],
       [-0.00306778, -0.00233635,  0.02477036, -0.00233099, -0.00231473,
        -0.00226766, -0.0022925 , -0.00158168, -0.00164941, -0.00233585,
        -0.00229823, -0.00229518],
       [-0.00231444, -0.00231753, -0.00233099,  0.02476277, -0.00229527,
        -0.0017295 , -0.00221663, -0.00229661, -0.00293126, -0.00233544,
        -0.00234931, -0.00164578],
       [-0.00231485, -0.00231617, -0.00231473, -0.00229527,  0.02550349,
        -0.00229233, -0.00226597, -0.00229518, -0.00233136, -0.00235706,
        -0.0030898 , -0.00163076],
       [-0.0023182 , -0.00238962, -0.00226766, -0.0017295 , -0.00229233,
         0.02086316,  

In [81]:
# the determinant is a huge number... at least it is not zero
np.linalg.det(wnba_massey_np)

692.4653280339061

In [82]:
# the rref does not look right either. It shows that the matrix is not full rank.
sympy.Matrix(wnba_massey_np).rref()

(Matrix([
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, -1],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, -1],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, -1],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, -1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, -1],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, -1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, -1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0]]),
 (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10))

The goal is in trying to ensure that we can have massey matrix as the A and the differential as the b. Hence, we can then solve $\vec{x}$ with $A\vec{x} = \vec{b}$

To do that, we need to have the massey matrix invertible. As seen above, we cannot do so in its current form. What's the solution then? We need to adjust the massey matrix with the following - 

1. add a row of 1's on the bottom of the matrix 
2. add a column of -1's to the far right of A
3. add 0 to the bottom of the vector of point differentials 


In [94]:
# append row of 1s and column of -1 to massey. Note here that -1 has 12 rows, and 1 has 13 columns.
row_of_ones = np.full((1,13), 1)
col_of_minus_ones = np.full((12,1), -1)
# appends the column. arg = 1 to append as a column. Otherwise, numpy will flatten the array
adj_wnba_massey_np = np.append(wnba_massey_np, col_of_minus_ones, axis = 1)
# append row. In here, you will have to add arg axis = 0 to show that this is to be added as a row
adj_wnba_massey_np = np.append(adj_wnba_massey_np, row_of_ones, axis = 0)
print (adj_wnba_massey_np)

[[33 -4 -2 -3 -3 -3 -3 -3 -3 -3 -3 -3 -1]
 [-4 33 -3 -3 -3 -3 -2 -3 -3 -3 -3 -3 -1]
 [-2 -3 34 -3 -3 -3 -3 -4 -4 -3 -3 -3 -1]
 [-3 -3 -3 34 -3 -4 -3 -3 -2 -3 -3 -4 -1]
 [-3 -3 -3 -3 33 -3 -3 -3 -3 -3 -2 -4 -1]
 [-3 -3 -3 -4 -3 41 -8 -3 -6 -3 -2 -3 -1]
 [-3 -2 -3 -3 -3 -8 41 -3 -4 -3 -3 -6 -1]
 [-3 -3 -4 -3 -3 -3 -3 34 -3 -2 -3 -4 -1]
 [-3 -3 -4 -2 -3 -6 -4 -3 38 -3 -4 -3 -1]
 [-3 -3 -3 -3 -3 -3 -3 -2 -3 32 -4 -2 -1]
 [-3 -3 -3 -3 -2 -2 -3 -3 -4 -4 33 -3 -1]
 [-3 -3 -3 -4 -4 -3 -6 -4 -3 -2 -3 38 -1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1]]


In [101]:
# append 0 to the differentials vector
wnba_diff_np = wnba_diff.to_numpy()
wnba_diff_np = np.append(wnba_diff_np, 0)
print (wnba_diff_np)

[-135 -171  152 -104 -308  292  420   83   -4 -213   -5   -7    0]


With the adjustments done, we can start to solve by:

1. Obtaining the inverse of A
2. Apply the inverse to the differentials

In [105]:
adj_wnba_inv = np.linalg.inv(adj_wnba_massey_np)
adj_wnba_inv[:5]

array([[0.0324498 , 0.00540293, 0.00387667, 0.00463   , 0.00462959,
        0.00462624, 0.00461111, 0.00460921, 0.00461055, 0.00463025,
        0.00462921, 0.00462777, 0.08333333],
       [0.00540293, 0.03244679, 0.00460809, 0.00462691, 0.00462827,
        0.00455483, 0.0039852 , 0.00462773, 0.00460802, 0.00463108,
        0.00463119, 0.0045823 , 0.08333333],
       [0.00387667, 0.00460809, 0.03171481, 0.00461345, 0.00462971,
        0.00467679, 0.00465194, 0.00536276, 0.00529504, 0.0046086 ,
        0.00464622, 0.00464926, 0.08333333],
       [0.00463   , 0.00462691, 0.00461345, 0.03170722, 0.00464917,
        0.00521494, 0.00472781, 0.00464783, 0.00401319, 0.00460901,
        0.00459513, 0.00529867, 0.08333333],
       [0.00462959, 0.00462827, 0.00462971, 0.00464917, 0.03244794,
        0.00465211, 0.00467848, 0.00464926, 0.00461309, 0.00458738,
        0.00385464, 0.00531369, 0.08333333]])

In [109]:
# time to solve
r = adj_wnba_inv@wnba_diff_np
r.round(3)

array([-4.013, -5.156,  4.31 , -2.608, -8.533,  7.85 , 10.612,  2.542,
        0.898, -6.182, -0.267,  0.547,  0.   ])

### Putting it back to the dataframe

With this solved, we can append it back to which ever dataframe to see which state did the best

In [113]:
R = r[:-1]

array([-4.01293846, -5.15625981,  4.30952472, -2.60812898, -8.53295813,
        7.85032664, 10.61241455,  2.54156514,  0.89791105, -6.1815735 ,
       -0.2666953 ,  0.54681208])

In [114]:
wnba_massey['Rating'] = R.tolist()

In [118]:
wnba_massey.sort_values(by = 'Rating', ascending = False)['Rating']

Team
Minnesota      10.612415
Los.Angeles     7.850327
Connecticut     4.309525
New.York        2.541565
Phoenix         0.897911
Washington      0.546812
Seattle        -0.266695
Dallas         -2.608129
Atlanta        -4.012938
Chicago        -5.156260
San.Antonio    -6.181574
Indiana        -8.532958
Name: Rating, dtype: float64